baseurl = "/"
languageCode = "en-us"
theme = "hugo-theme-terminal"
paginate = 5

[params]
  contentTypeName = "posts"
  themeColor = "pink"
  showMenuItems = 3
  fullWidthTheme = false
  centerTheme = false

[languages]
  [languages.en]
    title = "Savannah Ostrowski"
    subtitle = "Personal Site"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "Savannah Ostrowski"
      logoHomeLink = "/"
      identifier="home"
      

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/"

      [[languages.en.menu.main]]
        identifier="appearances"
        name="Appearances + Articles"
        url="/appearances"

      [[languages.en.menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/blog"